no-tests = true
output = "models"
wipe = true

[mysql]
dbname = "DataPlatformMastersAndTransactionsMysqlKube"
host = "XXXXXXXXXXXXXXX"
port = 30010
user = "XXXXXXXXXXXXXXX"
pass = "XXXXXXXXXXXXXXX"
sslmode = "false"
whitelist = [ "data_platform_business_partner_general_data" ]
