no-tests = true
output = "models"
wipe = true

[mysql]
dbname = "DataPlatformMastersAndTransactionsMysqlKube"
host = "XXXXXXXXXX"
port = 30010
user = "XXXXXXXXXX"
pass = "XXXXXXXXXX"
sslmode = "false"
whitelist = [ "data_platform_business_partner_general_data" ]
